name: Process Contact Form

on:
  repository_dispatch:
    types: [contact_form]

jobs:
  process-contact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Nouveau message de ${{github.event.client_payload.name}} - ${{github.event.client_payload.subject}}
          body: |
            <h2>Nouveau message depuis votre portfolio</h2>
            <p><strong>Nom:</strong> ${{github.event.client_payload.name}}</p>
            <p><strong>Email:</strong> ${{github.event.client_payload.email}}</p>
            <p><strong>Sujet:</strong> ${{github.event.client_payload.subject}}</p>
            <p><strong>Message:</strong></p>
            <p>${{github.event.client_payload.message}}</p>
          to: sergie.king5@gmail.com
          from: Portfolio Contact
          content_type: text/html
          secure: true
